version: "3"

services: 
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_cache:/var/lib/redis

  queuer:
    build: queuer
    depends_on: 
      - redis
    environment:
      - RUST_LOG=ERROR

  deduplicator:
    build: deduplicator
    depends_on:
      - redis
    environment:
      - RUST_LOG=ERROR

  namextractor:
    build: namextractor
    depends_on:
      - redis
    environment:
      - LOGURU_LEVEL=INFO

  tagificator:
    build: tagificator
    depends_on:
      - redis
    environment:
      - LOGURU_LEVEL=INFO

  rss-importer:
    build: rss-importer
    depends_on: 
      - queuer
    environment: 
      - QUEUER_URI=http://queuer:8000/submit

volumes: 
  redis_cache:
